### ISSUE TITLE
error while initialize test runner

### ISSUE THREAD

**Issue by pyogesh2** [naver/ngrinder#196]
Hello,

I get an error from my script - During Validation it says error while initialize test runner.
Can somebody help here to resolve the same ? Any hints.

016-08-31 05:10:41,519 INFO  The Grinder version 3.9.1
2016-08-31 05:10:41,523 INFO  OpenJDK Runtime Environment 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14: OpenJDK 64-Bit Server VM (25.91-b14, mixed mode) on Linux amd64 4.4.0-34-generic
2016-08-31 05:10:41,527 INFO  time zone is UTC (+0000)
2016-08-31 05:10:41,603 INFO  worker process 0 of agent number 0
2016-08-31 05:10:41,626 INFO  Instrumentation agents: byte code transforming instrumenter for Java; byte code transforming instrumenter for Java
2016-08-31 05:10:42,687 INFO  registered plug-in net.grinder.plugin.http.HTTPPlugin
2016-08-31 05:10:42,712 ERROR Script error - Error while initialize test runner
net.grinder.engine.common.EngineException: Error while initialize test runner
	at net.grinder.scriptengine.groovy.GroovyScriptEngine.<init>(GroovyScriptEngine.java:71) ~[ngrinder-groovy-3.4.jar:na]
	at net.grinder.scriptengine.groovy.GroovyScriptEngineService.createScriptEngine(GroovyScriptEngineService.java:109) ~[ngrinder-groovy-3.4.jar:na]
	at net.grinder.engine.process.ScriptEngineContainer.getScriptEngine(ScriptEngineContainer.java:105) ~[grinder-core-3.9.1.jar:na]
	at net.grinder.engine.process.GrinderProcess.run(GrinderProcess.java:330) ~[ngrinder-runtime-3.4.jar:na]
	at net.grinder.engine.process.WorkerProcessEntryPoint.run(WorkerProcessEntryPoint.java:87) [grinder-core-3.9.1.jar:na]
	at net.grinder.engine.process.WorkerProcessEntryPoint.main(WorkerProcessEntryPoint.java:60) [grinder-core-3.9.1.jar:na]
Caused by: net.grinder.scriptengine.groovy.GroovyScriptEngine$GroovyScriptExecutionException: Exception occurs in @BeforeProcess block.
	at net.grinder.scriptengine.groovy.GrinderContextExecutor.runBeforeProcess(GrinderContextExecutor.java:88) ~[ngrinder-groovy-3.4.jar:na]
	at net.grinder.scriptengine.groovy.GroovyScriptEngine.<init>(GroovyScriptEngine.java:64) ~[ngrinder-groovy-3.4.jar:na]
	... 5 common frames omitted
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.codehaus.groovy.runtime.dgmimpl.arrays.ObjectArrayGetAtMetaMethod.invoke(ObjectArrayGetAtMetaMethod.java:38) ~[groovy-all-2.2.1.jar:2.2.1]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233) ~[groovy-all-2.2.1.jar:2.2.1]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.invoke(PojoMetaMethodSite.java:48) ~[groovy-all-2.2.1.jar:2.2.1]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53) ~[groovy-all-2.2.1.jar:2.2.1]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45) ~[groovy-all-2.2.1.jar:2.2.1]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108) ~[groovy-all-2.2.1.jar:2.2.1]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116) ~[groovy-all-2.2.1.jar:2.2.1]
	at PersistenceTest.beforeClass(PersistenceNightly.groovy:64) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44) ~[junit-dep-4.8.2.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) ~[junit-dep-4.8.2.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41) ~[junit-dep-4.8.2.jar:na]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27) ~[junit-dep-4.8.2.jar:na]
	at net.grinder.scriptengine.groovy.GrinderContextExecutor.runBeforeProcess(GrinderContextExecutor.java:86) ~[ngrinder-groovy-3.4.jar:na]
	... 6 common frames omitted

2016-08-31 05:10:42,713 ERROR worker-bootstrap: Error running worker process
net.grinder.engine.common.EngineException: Error while initialize test runner
	at net.grinder.scriptengine.groovy.GroovyScriptEngine.<init>(GroovyScriptEngine.java:71) ~[ngrinder-groovy-3.4.jar:na]
	at net.grinder.scriptengine.groovy.GroovyScriptEngineService.createScriptEngine(GroovyScriptEngineService.java:109) ~[ngrinder-groovy-3.4.jar:na]
	at net.grinder.engine.process.ScriptEngineContainer.getScriptEngine(ScriptEngineContainer.java:105) ~[grinder-core-3.9.1.jar:na]
	at net.grinder.engine.process.GrinderProcess.run(GrinderProcess.java:330) ~[ngrinder-runtime-3.4.jar:na]
	at net.grinder.engine.process.WorkerProcessEntryPoint.run(WorkerProcessEntryPoint.java:87) [grinder-core-3.9.1.jar:na]
	at net.grinder.engine.process.WorkerProcessEntryPoint.main(WorkerProcessEntryPoint.java:60) [grinder-core-3.9.1.jar:na]
Caused by: net.grinder.scriptengine.groovy.GroovyScriptEngine$GroovyScriptExecutionException: Exception occurs in @BeforeProcess block.
	at net.grinder.scriptengine.groovy.GrinderContextExecutor.runBeforeProcess(GrinderContextExecutor.java:88) ~[ngrinder-groovy-3.4.jar:na]
	at net.grinder.scriptengine.groovy.GroovyScriptEngine.<init>(GroovyScriptEngine.java:64) ~[ngrinder-groovy-3.4.jar:na]
	... 5 common frames omitted
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.codehaus.groovy.runtime.dgmimpl.arrays.ObjectArrayGetAtMetaMethod.invoke(ObjectArrayGetAtMetaMethod.java:38) ~[groovy-all-2.2.1.jar:2.2.1]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233) ~[groovy-all-2.2.1.jar:2.2.1]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.invoke(PojoMetaMethodSite.java:48) ~[groovy-all-2.2.1.jar:2.2.1]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53) ~[groovy-all-2.2.1.jar:2.2.1]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45) ~[groovy-all-2.2.1.jar:2.2.1]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108) ~[groovy-all-2.2.1.jar:2.2.1]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116) ~[groovy-all-2.2.1.jar:2.2.1]
	at PersistenceTest.beforeClass(PersistenceNightly.groovy:64) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44) ~[junit-dep-4.8.2.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) ~[junit-dep-4.8.2.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41) ~[junit-dep-4.8.2.jar:na]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27) ~[junit-dep-4.8.2.jar:na]
	at net.grinder.scriptengine.groovy.GrinderContextExecutor.runBeforeProcess(GrinderContextExecutor.java:86) ~[ngrinder-groovy-3.4.jar:na]
	... 6 common frames omitted
+

Thanks !

**Comment by songeunwoo** [comment]
hello pyogesh2.

nGrinder supports JUnit 4.8 only, 
it seems that you mistakenly import above JUnit 4.8 in your pom.xml. 
Please exclude it.

thank you.
