### ISSUE TITLE
SSL Exception Error

### ISSUE THREAD

**Issue by InH4te** [naver/ngrinder#200]
Hi,

I'm using the following Jython code in nGrinder to try and retrieve the status code of a particular URL.

```
import urllib2

#Setting proxy
myProxy = {'https':'https://proxy.example.com:8080'}
proxy = urllib2.ProxyHandler(myProxy)
opener = urllib2.build_opener(proxy)
urllib2.install_opener(opener)

#Access URL
auth_token = "realLy_loNg_AuTheNicaTion_toKen"
headers={"Content-Type":"application/json",
         "charset": "UTF-8",
         "Authorization": "Bearer %s" %auth_token}
url = "https://example.com/something"
req = urllib2.Request(url, None, headers)
reply = urllib2.urlopen(req)
print reply.getcode()
```

When I run the same script on my system with Jython, it works fine and returns 200(OK status code). When I validate it on nGrinder, I get the error

`(-1, 'SSL exception: Differences between the SSL socket behaviour of cpython vs. jython are explained on the wiki:  http://wiki.python.org/jython/NewSocketModule#SSL_Support')`

There was a similar question posted [here ](http://stackoverflow.com/questions/33912074/https-get-using-jython)before. I read it but it wasn't described properly. But it could be a good reference to think off of.

Any ideas why this is happening, I've been trying to crack this for sometime now?

**Comment by songeunwoo** [comment]
Hi InH4te,
please post your script.
and error log plz..

**Comment by InH4te** [comment]
Thanks a lot for your quick reply. I really need to know why this isn't working! Below is my entire StatusReturn.py script.

```
from net.grinder.script.Grinder import grinder
from net.grinder.script import Test
from net.grinder.plugin.http import HTTPRequest
from net.grinder.plugin.http import HTTPPluginControl
from java.util import Date
from HTTPClient import NVPair, Cookie, CookieModule
import urllib2

control = HTTPPluginControl.getConnectionDefaults()
control.timeout = 6000

auth_token="abcd-EcfSoak-xsorFD-reAlly-looooNg"
test1 = Test(1, "https://test.example.com/Sample/Things?$id=60")

class TestRunner:
	# initlialize a thread 
	def __init__(self):
		test1.record(TestRunner.__call__)
		grinder.statistics.delayReports=True
		pass
	
	def before(self):
		myProxy = {'https':'https://proxy.example.org:8080'}
		proxy = urllib2.ProxyHandler(myProxy)
		opener = urllib2.build_opener(proxy)
		urllib2.install_opener(opener)

	# test method		
	def __call__(self):
		self.before()
		headers={"Content-Type":"application/json",
		 "charset": "UTF-8",
		 "Authorization":"Bearer %s " %auth_token}
		url = "https://test.example.com/Sample/Things?$id=60"
		req = urllib2.Request(url, None, headers)
		try:
			reply = urllib2.urlopen(req)
			print reply.getcode()
		except urllib2.URLError, e:
			print e.reason
```

And my error log comes normally but since I've written it as an exception, it gets caught and printed out at the end of the log file as so
`
(-1, 'SSL exception: Differences between the SSL socket behaviour of cpython vs. jython are explained on the wiki:  http://wiki.python.org/jython/NewSocketModule#SSL_Support')`

Do you still want the output?

**Comment by junoyoon** [comment]
As the output said... it's due to different b/w cpython and jython. ngrinder uses jython.

I'd recommend to use http://grinder.sourceforge.net/g3/http-plugin.html#Setting+an+HTTP+proxy

**Comment by InH4te** [comment]
Thanks for the reply. Will try this out and revert.

But how is it that it was working with my system's Jython interpreter?

**Comment by InH4te** [comment]
Went through the links and replaced my code with the following

```
from net.grinder.script.Grinder import grinder
from net.grinder.script import Test
from net.grinder.plugin.http import HTTPRequest, HTTPPluginControl
from HTTPClient import NVPair

statusReturn = Test(1, "Return status code of given URL")
request = HTTPRequest()
control = HTTPPluginControl.getConnectionDefaults()
statusReturn.record(request)

control.setProxyServer("https://proxy.example.com", 8080)
headers = [
	NVPair('Content-Type', 'application/json'),
	NVPair('charset', 'UTF-8'),
	NVPair('Authorization', 'Bearer xsEos3l-Xoqusrocsl_soqusmZlsoe'),
]

#Instance is created for every thread
class TestRunner:
	def __call__(self):
		#Method called for every thread
		url = "https://example.com/something-page/id=60"
		result = request.GET(url, None, headers)
		print result.getStatusCode()
```
But, am getting the following output:

```
2016-09-12 06:26:29,808 INFO  The Grinder version 3.9.1
2016-09-12 06:26:29,812 INFO  OpenJDK Runtime Environment 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14: OpenJDK 64-Bit Server VM (25.91-b14, mixed mode) on Linux amd64 4.4.0-36-generic
2016-09-12 06:26:29,816 INFO  time zone is UTC (+0000)
2016-09-12 06:26:29,885 INFO  worker process 0 of agent number 0
2016-09-12 06:26:29,932 INFO  Instrumentation agents: byte code transforming instrumenter for Jython 2.5; byte code transforming instrumenter for Java
2016-09-12 06:26:31,185 INFO  registered plug-in net.grinder.plugin.http.HTTPPlugin
2016-09-12 06:26:31,262 INFO  Running "URLStatus.py" using Jython 2.5.3 (2.5:c56500f08d34+, Aug 13 2012, 14:54:35) 
[OpenJDK 64-Bit Server VM (Oracle Corporation)]
2016-09-12 06:26:31,297 INFO  starting, will do 1 run
2016-09-12 06:26:31,297 INFO  Start time is 1473661591298 ms since Epoch
2016-09-12 06:26:31,401 ERROR Aborted run: Java exception calling TestRunner
net.grinder.scriptengine.jython.JythonScriptExecutionException: Java exception calling TestRunner
	result = request.GET(url, None, headers)
	File "${NGRINDER_HOME}/script/admin/URLStatus.py", line 32, in __call__
java.net.UnknownHostException: https://proxy.example.com
	at org.ngrinder.dns.LocalManagedDnsImpl.lookupAllHostAddr(LocalManagedDnsImpl.java:53) ~[ngrinder-runtime-3.4.jar:na]
	at org.ngrinder.dns.LocalManagedDnsProxy.lookupAllHostAddr(LocalManagedDnsProxy.java:63) ~[ngrinder-runtime-3.4.jar:na]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[na:1.8.0_91]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276) ~[na:1.8.0_91]
	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[na:1.8.0_91]
	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[na:1.8.0_91]
	at HTTPClient.HTTPConnection.getSocket(HTTPConnection.java:3395) ~[grinder-httpclient-3.9.1.jar:na]
	at HTTPClient.HTTPConnection.sendRequest(HTTPConnection.java:3089) ~[grinder-httpclient-3.9.1.jar:na]
	at HTTPClient.HTTPConnection.handleRequest(HTTPConnection.java:2883) ~[grinder-httpclient-3.9.1.jar:na]
	at HTTPClient.HTTPConnection.setupRequest(HTTPConnection.java:2675) ~[grinder-httpclient-3.9.1.jar:na]
	at HTTPClient.HTTPConnection.Get(HTTPConnection.java:986) ~[grinder-httpclient-3.9.1.jar:na]
	at net.grinder.plugin.http.HTTPRequest$2.doRequest(HTTPRequest.java:504) ~[grinder-http-3.9.1.jar:na]
	at net.grinder.plugin.http.HTTPRequest$AbstractRequest.getHTTPResponse(HTTPRequest.java:1276) ~[grinder-http-3.9.1.jar:na]
	at net.grinder.plugin.http.HTTPRequest.GET(HTTPRequest.java:499) ~[grinder-http-3.9.1.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyObject.__call__(PyObject.java:441) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyObject.__call__(PyObject.java:447) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:154) ~[jython-standalone-2.5.3.jar:na]
	at org.python.pycode._pyx1.__call__$2(${NGRINDER_HOME}/script/admin/URLStatus.py:36) ~[na:na]
	at org.python.pycode._pyx1.call_function(${NGRINDER_HOME}/script/admin/URLStatus.py) ~[na:na]
	at org.python.core.PyTableCode.call(PyTableCode.java:165) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:301) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:194) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyFunction.__call__(PyFunction.java:387) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:220) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:211) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:206) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyObject.invoke(PyObject.java:3555) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyInstance.instance___call__(PyInstance.java:351) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyInstance.__call__(PyInstance.java:342) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyObject.__call__(PyObject.java:371) ~[jython-standalone-2.5.3.jar:na]
	at net.grinder.scriptengine.jython.JythonScriptEngine$JythonWorkerRunnable.run(JythonScriptEngine.java:250) ~[grinder-core-3.9.1.jar:na]
	at net.grinder.engine.process.GrinderThread.run(GrinderThread.java:118) ~[grinder-core-3.9.1.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
2016-09-12 06:26:31,402 INFO  finished 1 run
2016-09-12 06:26:31,404 INFO  elapsed time is 106 ms
2016-09-12 06:26:31,404 INFO  Final statistics for this process:
2016-09-12 06:26:31,412 INFO  
             Tests        Errors       Mean Test    Test Time    TPS          Mean         Response     Response     Mean time to Mean time to Mean time to 
                                       Time (ms)    Standard                  response     bytes per    errors       resolve host establish    first byte   
                                                    Deviation                 length       second                                 connection                
                                                    (ms)                                                                                                    

Test 1       0            1            �            0.00         0.00         �            0.00         0            �            �            �             "Return status code of given URL"

Totals       0            1            �            0.00         0.00         �            0.00         0            �            �            �            

  Tests resulting in error only contribute to the Errors column.          
  Statistics for individual tests can be found in the data file, including
  (possibly incomplete) statistics for erroneous tests. Composite tests   
  are marked with () and not included in the totals.                      



2016-09-12 06:26:31,266 INFO  validation-0: Starting threads
2016-09-12 06:26:31,412 INFO  validation-0: Finished

+

```
Any help would be appreciated!

**Comment by InH4te** [comment]
It looks like the issue was with the syntax by which I gave the proxy.
Changed this 
`control.setProxyServer("https://proxy.example.com", 8080)`
to this
`control.setProxyServer("proxy.example.com", 8080)`

And it all worked.
