### ISSUE TITLE
Error while executing test,controller log tips:is not completed until Connection 10 sec

### ISSUE THREAD

**Issue by ngrinder520** [naver/ngrinder#210]
version:ngrinder3.4
When using the five proxy and Vuser is equal to 15000, Error while executing test, controller log  tips: is not completed until Connection 10 sec.
when using the four proxy and Vuser less than 15000，Run after display：the test is finished but has no tps，controller log  tips:WARN  PerfTestService.java:713 : Report TPS for test 377 does not exist.

**Comment by songeunwoo** [comment]
Hi @ngrinder520 
Can you see the agent-log file?

**Comment by ngrinder520** [comment]
hi，songeunwoo
agent log tips：
2016-09-28 11:38:49,030 INFO  agent controller  :  Received a start agent message
2016-09-28 11:38:49,031 INFO  agent controller  :  Agent start message is received from       controller net.grinder.messages.agent.StartGrinderMessage@1e7f8c99
2016-09-28 11:38:49,031 INFO  agent controller  :  Starting agent... for test_385
2016-09-28 11:38:49,031 INFO  agent daemon  :  Agent daemon connecting to port 12001 is       started.
2016-09-28 11:38:49,031 INFO  agent controller  :  Agent is started. Waiting for agent       controller signal
2016-09-28 11:38:59,042 ERROR net.grinder.util.NetworkUtils  :  Error while get localho      st name
java.net.UnknownHostException: im39: im39: unknown error
        at java.net.InetAddress.getLocalHost(InetAddress.java:1505) ~[na:1.8.0_101]
        at net.grinder.util.NetworkUtils.getLocalHostName(NetworkUtils.java:185) ~[ngri      nder-core-3.4.jar:na]
        at net.grinder.engine.agent.AgentImplementationEx.<init>(AgentImplementationEx.      java:97) [ngrinder-core-3.4.jar:na]
        at net.grinder.engine.agent.AgentImplementationEx.<init>(AgentImplementationEx.      java:108) [ngrinder-core-3.4.jar:na]
        at net.grinder.AgentDaemon$AgentThreadRunnable.run(AgentDaemon.java:132) [ngrin      der-core-3.4.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
Caused by: java.net.UnknownHostException: im39: unknown error
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_101]
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[na:1.8.0_10      1]
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[na      :1.8.0_101]
        at java.net.InetAddress.getLocalHost(InetAddress.java:1500) ~[na:1.8.0_101]
        ... 5 common frames omitted
2016-09-28 11:39:01,099 INFO  agent daemon  :  The Grinder 3.9.1
2016-09-28 11:39:01,100 ERROR agent daemon  :  Failed to connect to '/10.111.96.39:1200      1'
2016-09-28 11:39:01,100 INFO  agent daemon  :  Test shuts down.
2016-09-28 11:39:01,100 INFO  agent controller  :  Send log for test_385

**Comment by ngrinder520** [comment]
Simultaneous operation of the 5 agents, only some agents are not connected to the controller 12001 port

**Comment by ngrinder520** [comment]
The same agent is sometimes connected to the controller of 12001 port, and sometimes it is not on the connection

**Comment by songeunwoo** [comment]
did u add the target host(monitoring target) in the test configuration?

![1475040157558](https://cloud.githubusercontent.com/assets/16470009/18901574/100f72e2-8587-11e6-99b0-892ecd902f10.jpg)

**Comment by ngrinder520** [comment]
hi，songeunwoo 
i added monitor‘s ip in test target host，no add domain in  test target host

**Comment by songeunwoo** [comment]
I hope try to add the test to the target host.
See the bottom link.
http://www.cubrid.org/wiki_ngrinder/entry/how-to-change-dns
and..
try telnet test?

**Comment by ngrinder520** [comment]
1.after added ip in the target host，When using the 5 proxy run, still don't running test，page tips：stoped by error，controller log info：Error while executing test, controller log tips: is not completed until Connection 10 sec.
2.Using three agents can be to successfully perform the test

**Comment by ngrinder520** [comment]
A controller can support a maximum of several agents? 
Why can't 5 agents perform the test？

**Comment by ngrinder520** [comment]
How to configure to use more than 10 agents？

**Comment by songeunwoo** [comment]
you can change systemconfig file.
menu > id > system Configuration > change controller.max_agent_per_test count.

![2016-09-28 7 11 35](https://cloud.githubusercontent.com/assets/16470009/18909790/f3f1c1d6-85af-11e6-8780-cc5099682ebd.png)
![2016-09-28 7 12 25](https://cloud.githubusercontent.com/assets/16470009/18909796/f874e044-85af-11e6-95ad-a0aac8efcc92.png)


and run agents.

```
./run_agent.sh --agent-home ~/.ngrinde-agent-1 --host-id agent1
./run_agent.sh --agent-home ~/.ngrinde-agent-2 --host-id agent2
...
```
good luck~

**Comment by ngrinder520** [comment]
I know this configuation，but，
1.When using the five  proxys to run, still don't running test，page tips：stoped by error，controller log info：Error while executing test, controller log tips: is not completed until Connection 10 sec.
2.Using three agents can be to successfully perform the test

**Comment by ngrinder520** [comment]
Can you use QQ to communicate with you
？

**Comment by junoyoon** [comment]
it's really weird to see the following message.

```
2016-09-28 11:38:49,030 INFO agent controller : Received a start agent message
2016-09-28 11:38:49,031 INFO agent controller : Agent start message is received from controller net.grinder.messages.agent.StartGrinderMessage@1e7f8c9
2016-09-28 11:38:49,031 INFO agent controller : Starting agent... for test_385
2016-09-28 11:38:49,031 INFO agent daemon : Agent daemon connecting to port 12001 is started.
2016-09-28 11:38:49,031 INFO agent controller : Agent is started. Waiting for agent controller signal
2016-09-28 11:38:59,042 ERROR net.grinder.util.NetworkUtils : Error while get localho st name
java.net.UnknownHostException: im39: im39: unknown error
at java.net.InetAddress.getLocalHost(InetAddress.java:1505) ~[na:1.8.0_101]
at net.grinder.util.NetworkUtils.getLocalHostName(NetworkUtils.java:185) ~[ngri nder-core-3.4.jar:na]
at net.grinder.engine.agent.AgentImplementationEx.(AgentImplementationEx. java:97) [ngrinder-core-3.4.jar:na]
at net.grinder.engine.agent.AgentImplementationEx.(AgentImplementationEx. java:108) [ngrinder-core-3.4.jar:na]
at net.grinder.AgentDaemon$AgentThreadRunnable.run(AgentDaemon.java:132) [ngrin der-core-3.4.jar:na]
at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
Caused by: java.net.UnknownHostException: im39: unknown error
at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_101]
at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[na:1.8.0_10 1]
at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[na :1.8.0_101]
at java.net.InetAddress.getLocalHost(InetAddress.java:1500) ~[na:1.8.0_101]
... 5 common frames omitted
2016-09-28 11:39:01,099 INFO agent daemon : The Grinder 3.9.1
2016-09-28 11:39:01,100 ERROR agent daemon : Failed to connect to '/10.111.96.39:1200 1'
2016-09-28 11:39:01,100 INFO agent daemon : Test shuts down.
2016-09-28 11:39:01,100 INFO agent controller : Send log for test_385
```
especially the following parts.

```
 get localho st name
```

And.. did u run the multiple agents on the same host?
It's really not recommendable..  it's because each agent try to create threads in the same host. It affects each others.
Please split them into multiple servers.

In addition, did u check your ulimit configuration? I'm suspecting you didn't have enough ulimit configuration.
please check your ulimit configuration. especially open files should be very large.
```
[ ~]$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31184
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 81920
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 81920
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
[~]$
```
