### ISSUE TITLE
Thread has been shut down

### ISSUE THREAD

**Issue by gxdprivate** [naver/ngrinder#255]
when i was looked the runtime log ,i saw follow error message

i don't know how did this error happend ? so,need help. 

2017-10-20 17:54:38,566 ERROR Aborting thread: net.grinder.engine.process.ShutdownException: Thread has been shut down
net.grinder.engine.process.ShutdownException: Thread has been shut down
        at net.grinder.engine.process.ThreadContextImplementation.pushDispatchContext(ThreadContextImplementation.java:229) ~[ngrinder-runtime-3.4.1.jar:na]
        at net.grinder.engine.process.TestData$RecorderHolder.start(TestData.java:196) ~[grinder-core-3.9.1.jar:na]
        at net.grinder.engine.process.TestData.start(TestData.java:126) ~[grinder-core-3.9.1.jar:na]
        at net.grinder.engine.process.dcr.RecorderLocator.enter(RecorderLocator.java:120) ~[grinder-core-3.9.1.jar:na]
        at org.python.core.PyFunction.__call__(PyFunction.java) ~[jython-standalone-2.5.3.jar:na]
        at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:220) ~[jython-standalone-2.5.3.jar:na]
        at org.python.core.PyMethod.__call__(PyMethod.java:211) ~[jython-standalone-2.5.3.jar:na]
        at org.python.core.PyMethod.__call__(PyMethod.java:206) ~[jython-standalone-2.5.3.jar:na]
        at org.python.core.PyObject.invoke(PyObject.java:3555) ~[jython-standalone-2.5.3.jar:na]
        at org.python.core.PyInstance.instance___call__(PyInstance.java:351) ~[jython-standalone-2.5.3.jar:na]
        at org.python.core.PyInstance.__call__(PyInstance.java:342) ~[jython-standalone-2.5.3.jar:na]
        at org.python.core.PyObject.__call__(PyObject.java:371) ~[jython-standalone-2.5.3.jar:na]
        at net.grinder.scriptengine.jython.JythonScriptEngine$JythonWorkerRunnable.run(JythonScriptEngine.java:250) ~[grinder-core-3.9.1.jar:na]
        at net.grinder.engine.process.GrinderThread.run(GrinderThread.java:118) ~[grinder-core-3.9.1.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]

**Comment by zhougy1989** [comment]
@junoyoon  why?

**Comment by junoyoon** [comment]
@zhougy1989 you know me?

**Comment by zhougy1989** [comment]
@junoyoon  you help me solve many questions,and this issue i meet it，too

**Comment by donggyu04** [comment]
@zhougy1989 

If you using the Jython script? if right check [this](https://github.com/naver/ngrinder/pull/817).
