### ISSUE TITLE
java.lang.Error: Unresolved compilation problems: 

### ISSUE THREAD

**Issue by caserffer** [naver/ngrinder#259]
i'm useing ngrinder lib feature to import java jar
but i encounter an error when i validate script,the log is as follow:
very happy for any help!

2017-10-31 16:13:28,219 INFO  The Grinder version 3.9.1
2017-10-31 16:13:28,231 INFO  Java(TM) SE Runtime Environment 1.8.0_131-b11: Java HotSpot(TM) 64-Bit Server VM (25.131-b11, mixed mode) on Windows 7 amd64 6.1
2017-10-31 16:13:28,236 INFO  time zone is CST (+0800)
2017-10-31 16:13:28,361 INFO  worker process 0 of agent number 0
2017-10-31 16:13:28,393 INFO  Instrumentation agents: byte code transforming instrumenter for Java; byte code transforming instrumenter for Java
2017-10-31 16:13:29,330 INFO  before process.
2017-10-31 16:13:29,333 INFO  Running "TestRunner.groovy" using GroovyScriptEngine running with groovy version: 2.2.1
2017-10-31 16:13:29,370 INFO  before thread.
2017-10-31 16:13:29,370 INFO  starting, will do 1 run
2017-10-31 16:13:29,370 INFO  Start time is 1509437609370 ms since Epoch
2017-10-31 16:13:30,290 ERROR null
java.lang.Error: Unresolved compilation problems: 
	The import com.cnc cannot be resolved
	The import com.cnc cannot be resolved
	The import com.cnc cannot be resolved
	The import com.cnc cannot be resolved
	The import com.cnc cannot be resolved
	The import com.cnc cannot be resolved
	The import com.cnc cannot be resolved
	The import com.cnc cannot be resolved
	Handler cannot be resolved to a type
	IdlInvocation cannot be resolved to a type
	IdlResult cannot be resolved to a type
	IdlInvocation cannot be resolved to a type
	IdlResult cannot be resolved to a type
	com.cnc cannot be resolved to a type
	com.cnc cannot be resolved to a type
	com.cnc cannot be resolved to a type
	com.cnc cannot be resolved to a type
	com.cnc cannot be resolved to a type
	com.cnc.dna.platform.thrift.protocol.TType cannot be resolved to a variable
	IScheme cannot be resolved to a type
	SchemeFactory cannot be resolved to a type
	IScheme cannot be resolved to a type
	SchemeFactory cannot be resolved to a type
	SchemeFactory cannot be resolved to a type
	IScheme cannot be resolved to a type
	StandardScheme cannot be resolved to a type
	SchemeFactory cannot be resolved to a type
	IScheme cannot be resolved to a type
	TupleScheme cannot be resolved to a type
	com.cnc cannot be resolved to a type
	com.cnc cannot be resolved to a type
	com.cnc cannot be resolved to a type
	com.cnc cannot be resolved to a type
	com.cnc cannot be resolved to a type
	com.cnc.dna.platform.thrift.TFieldRequirementType cannot be resolved to a variable
	com.cnc cannot be resolved to a type
	com.cnc.dna.platform.thrift.protocol.TType cannot be resolved to a variable
	FieldMetaData cannot be resolved to a type
	com.cnc.dna.platform.thrift.meta_data.FieldMetaData cannot be resolved to a type
	FieldMetaData cannot be resolved to a type
	SchemeFactory cannot be resolved to a type
	StandardScheme cannot be resolved to a type
	SchemeFactory cannot be resolved to a type
	TupleScheme cannot be resolved to a type
	com.cnc cannot be resolved to a type
	com.cnc cannot be resolved to a type
	com.cnc cannot be resolved to a type
	com.cnc cannot be resolved to a type
	com.cnc cannot be resolved to a type
	com.cnc.dna.platform.thrift.protocol.TType cannot be resolved to a variable
	IScheme cannot be resolved to a type
	SchemeFactory cannot be resolved to a type
	IScheme cannot be resolved to a type
	SchemeFactory cannot be resolved to a type
	SchemeFactory cannot be resolved to a type
	IScheme cannot be resolved to a type
	StandardScheme cannot be resolved to a type
	IScheme cannot be resolved to a type
	SchemeFactory cannot be resolved to a type
	TupleScheme cannot be resolved to a type
	com.cnc cannot be resolved to a type
	com.cnc cannot be resolved to a type
	com.cnc cannot be resolved to a type
	com.cnc cannot be resolved to a type
	com.cnc cannot be resolved to a type
	com.cnc.dna.platform.thrift.TFieldRequirementType cannot be resolved to a variable
	com.cnc cannot be resolved to a type
	com.cnc.dna.platform.thrift.protocol.TType cannot be resolved to a variable
	FieldMetaData cannot be resolved to a type
	com.cnc.dna.platform.thrift.meta_data.FieldMetaData cannot be resolved to a type
	FieldMetaData cannot be resolved to a type
	SchemeFactory cannot be resolved to a type
	StandardScheme cannot be resolved to a type
	SchemeFactory cannot be resolved to a type
	TupleScheme cannot be resolved to a type
	com.cnc cannot be resolved to a type
	com.cnc cannot be resolved to a type
	com.cnc cannot be resolved to a type
	com.cnc cannot be resolved to a type
	com.cnc cannot be resolved to a type
	com.cnc.dna.platform.thrift.protocol.TType cannot be resolved to a variable
	IScheme cannot be resolved to a type
	SchemeFactory cannot be resolved to a type
	IScheme cannot be resolved to a type
	SchemeFactory cannot be resolved to a type
	IScheme cannot be resolved to a type
	SchemeFactory cannot be resolved to a type
	StandardScheme cannot be resolved to a type
	IScheme cannot be resolved to a type
	com.cnc cannot be resolved to a type
	SchemeFactory cannot be resolved to a type
	StandardScheme cannot be resolved to a type
	SchemeFactory cannot be resolved to a type
	TupleScheme cannot be resolved to a type
	com.cnc cannot be resolved to a type
	com.cnc cannot be resolved to a type
	SchemeFactory cannot be resolved to a type
	StandardScheme cannot be resolved to a type
	SchemeFactory cannot be resolved to a type
	TupleScheme cannot be resolved to a type

	at dna.HelloWorld$hiInvocation.<init>(HelloWorld.java:11) ~[helloworld.jar:na]
	at com.cnc.thirdparty.lang3.reflect.ConstructorUtils.invokeConstructor(ConstructorUtils.java:118) ~[cnc-common-1.1.0.jar:na]
	at com.cnc.thirdparty.lang3.reflect.ConstructorUtils.invokeConstructor(ConstructorUtils.java:85) ~[cnc-common-1.1.0.jar:na]
	at com.cnc.dna.platform.rpc.spi.proxy.JdkInvokerProxyFactory$IfaceInvocationHandler.invoke(JdkInvokerProxyFactory.java:78) ~[cnc-java-sdk-dna-2.6.0.jar:na]
	at com.sun.proxy.$Proxy17.hi(Unknown Source) ~[na:na]
	at dna.HelloWorld$Iface$hi.call(Unknown Source) ~[na:na]
	at TestRunner.test(TestRunner.groovy:58) ~[na:na]
	at net.grinder.scriptengine.groovy.junit.GrinderRunner.run(GrinderRunner.java:170) ~[ngrinder-groovy-3.4.1.jar:na]
	at net.grinder.scriptengine.groovy.GroovyScriptEngine$GroovyWorkerRunnable.run(GroovyScriptEngine.java:147) ~[ngrinder-groovy-3.4.1.jar:na]
	at net.grinder.engine.process.GrinderThread.run(GrinderThread.java:118) ~[grinder-core-3.9.1.jar:na]
2017-10-31 16:13:30,292 INFO  finished 1 run
2017-10-31 16:13:30,294 INFO  elapsed time is 925 ms
2017-10-31 16:13:30,294 INFO  Final statistics for this process:

**Comment by aztekmq** [comment]
Hi, I'm having similar issue, I've been using the pre-compiled ngrinder.war file, I've not tried compiling the source.... 

A few interesting things I noticed:

1.)   the logs indicate variable ngrinder.jvm.classpath is having the fully qualified path to my jars in it, looks kosher.
2.)   when I check that physical path on the filesystem, the jars were NOT there. (the upload through web-ui does not appear to be working properly)
3.)   when I manually created the lib sub-directory matching the same sub-dir structure in the ngrinder.jvm.classpath from the log, then manually placed the jars there, restart, and it still could not find them, same error.

So I have no clue...
