### ISSUE TITLE
SSLHandshakeException

### ISSUE THREAD

**Issue by moonchanyong** [naver/ngrinder#284]
ssl handshakeexception오류로 고통받고있습니다. 
jython을 사용한 스트립트,  aws api gateway, docker agent 및 controler container 사용
해결 해보려고 docker 내 자바 홈의 jre security keystore에 인증서 추가해보고
tls 기본 버전 때문인지 jdk도 1.8로 해서 해보았습니다 (container)

혹시 이 문제 맞닥뜨린분 있으신지.. 아니면 SNI관련 설정을 하면 된다고하는데 사실 jython으로 어떻게 접근할지 감이안옵니다 조언 부탁드립니다 

-- error log 
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)]
2018-04-19 04:55:08,680 INFO  starting, will do 1 run
2018-04-19 04:55:08,681 INFO  Start time is 1524113708681 ms since Epoch
2018-04-19 04:55:08,995 ERROR Aborted run: Java exception calling TestRunner
net.grinder.scriptengine.jython.JythonScriptExecutionException: Java exception calling TestRunner
	result = request1.POST("https://frov6ccx5l.execute-api.ap-northeast-2.amazonaws.com/master/auth/login", params)
	File "${NGRINDER_HOME}/script/admin/arom_loadtesting.py", line 47, in __call__
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_92]
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154) ~[na:1.8.0_92]
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023) ~[na:1.8.0_92]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125) ~[na:1.8.0_92]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375) ~[na:1.8.0_92]
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:747) ~[na:1.8.0_92]
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123) ~[na:1.8.0_92]
	at java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:167) ~[na:1.8.0_92]
	at HTTPClient.HTTPConnection.sendRequest(HTTPConnection.java:3147) ~[grinder-httpclient-3.9.1.jar:na]
	at HTTPClient.HTTPConnection.handleRequest(HTTPConnection.java:2883) ~[grinder-httpclient-3.9.1.jar:na]
	at HTTPClient.HTTPConnection.setupRequest(HTTPConnection.java:2675) ~[grinder-httpclient-3.9.1.jar:na]
	at HTTPClient.HTTPConnection.Post(HTTPConnection.java:1177) ~[grinder-httpclient-3.9.1.jar:na]
	at HTTPClient.HTTPConnection.Post(HTTPConnection.java:1142) ~[grinder-httpclient-3.9.1.jar:na]
	at HTTPClient.HTTPConnection.Post(HTTPConnection.java:1100) ~[grinder-httpclient-3.9.1.jar:na]
	at net.grinder.plugin.http.HTTPRequest$6.doRequest(HTTPRequest.java:816) ~[grinder-http-3.9.1.jar:na]
	at net.grinder.plugin.http.HTTPRequest$AbstractRequest.getHTTPResponse(HTTPRequest.java:1276) ~[grinder-http-3.9.1.jar:na]
	at net.grinder.plugin.http.HTTPRequest.POST(HTTPRequest.java:811) ~[grinder-http-3.9.1.jar:na]
	at net.grinder.plugin.http.HTTPRequest.POST(HTTPRequest.java:788) ~[grinder-http-3.9.1.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyObject.__call__(PyObject.java:422) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyObject.__call__(PyObject.java:426) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:139) ~[jython-standalone-2.5.3.jar:na]
	at org.python.pycode._pyx1.__call__$4(${NGRINDER_HOME}/script/admin/arom_loadtesting.py:62) ~[na:na]
	at org.python.pycode._pyx1.call_function(${NGRINDER_HOME}/script/admin/arom_loadtesting.py) ~[na:na]
	at org.python.core.PyTableCode.call(PyTableCode.java:165) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:301) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:194) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyFunction.__call__(PyFunction.java:387) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:220) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:211) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:206) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyObject.invoke(PyObject.java:3555) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyInstance.instance___call__(PyInstance.java:351) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyInstance.__call__(PyInstance.java:342) ~[jython-standalone-2.5.3.jar:na]
	at org.python.core.PyObject.__call__(PyObject.java:371) ~[jython-standalone-2.5.3.jar:na]
	at net.grinder.scriptengine.jython.JythonScriptEngine$JythonWorkerRunnable.run(JythonScriptEngine.java:250) ~[grinder-core-3.9.1.jar:na]
	at net.grinder.engine.process.GrinderThread.run(GrinderThread.java:118) ~[grinder-core-3.9.1.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]
2018-04-19 04:55:09,003 INFO  finished 1 run

**Comment by joon1030** [comment]
https://stackoverflow.com/questions/6353849/received-fatal-alert-handshake-failure-through-sslhandshakeexception/52000542#52000542

요거 참고해보세요~!
