### ISSUE TITLE
How to close the HTTPRequest connection(avoid java.io.IOException in netty)

### ISSUE THREAD

**Issue by fishjam** [naver/ngrinder#289]
When I test a program written by netty. I received this error message after each test completed.
```
23:10:56.648 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xec183484, L:/0:0:0:0:0:0:0:0:8080] READ COMPLETE
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

It seems that ngrinder will not close the http connection? Because I write a simple client and don't close the connection, it will result same error.

I tried some method, but can not fix it. 
- new NVPair("Connection", "Close") in header.
- result.getInputStream().close()

## Step to reproduce this issue
 - use ngrinder to test netty's simple example: [helloworld](https://github.com/netty/netty/tree/4.1/example/src/main/java/io/netty/example/http/helloworld). Then you will find it in helloworld's output.

**Comment by junoyoon** [comment]
Async HTTPCleitn like Netty is not well working in nGrinder. Please do not use Netty.
If u still need to use Netty...  U need to find out how to make a call sync way.

**Comment by fishjam** [comment]
In this issue, netty is a server, it accept any incoming connection from client( Chrome, ngrinder). 
I think the reason is that grinder did not close the connection before it quit.

**Comment by fishjam** [comment]
After some debug and compare with other http sdk(apache.httpcomponents and vertx, etc), I found grinder will not close the socket before test case quit. The server will receive TCP RST, even the server is Spring Boot with tomcat. 
![image](https://user-images.githubusercontent.com/1870684/42125991-1e89f49e-7cb3-11e8-98b2-a8def0dd3536.png)

I think this is a potential bug. The difference is netty print error log, and tomcat in spring just ignore it.

And this is my temporary solution: add a close method in StreamDemultiplexor to close the socket.
```
  void close() {
    Socket tmpSock = Sock;
    Sock = null;
    try {
      tmpSock.setSoLinger(false, 0); //disable SO_LINGER, otherwise server will RST
      tmpSock.getOutputStream().flush();
      //tmpSock.getOutputStream().close();
      //tmpSock.getInputStream().close();
      tmpSock.close();
    } catch (IOException e) {
      e.printStackTrace();
    }
  }
```

Additional Information
 - 1. There are lots of clean logical(abort, closeSocketIfAllStreamsClosed) in StreamDemultiplexor.java, this simple close just a demonstration, so can  close the socket without cause netty error.
 - 2.Of course, this is not a serious problem, grinder is performance test tool, it will not cause any problems on real environment.

**Comment by fishjam** [comment]
Sorry, after more study about grinder's code, I think grinder setSoLinger(true, 0) and doesn't close the socket safely is trying to reduce TIME_WAIT. so grinder can re-use the socket to send another request immediately. 
But I think setReuseAddress is better, is not it?
