### ISSUE TITLE
升级到slf4j提示错误，如何解决

### ISSUE THREAD

**Issue by keny16888** [naver/ngrinder#316]
升级备注：

<dependency>
   <groupId>ch.qos.logback</groupId>
   <artifactId>logback-classic</artifactId>
   <version>1.1.11</version>
</dependency>

<dependency>
   <groupId>org.slf4j</groupId>
   <artifactId>jcl-over-slf4j</artifactId>
   <version>1.7.25</version>
   <scope>runtime</scope>
</dependency>
<dependency>
   <groupId>org.slf4j</groupId>
   <artifactId>slf4j-api</artifactId>
   <version>1.7.25</version>
</dependency>
4.调试：
提示错误：

2018-08-15 10:43:11,251 ERROR Script error - Error while initialize test runner
net.grinder.engine.common.EngineException: Error while initialize test runner
	at net.grinder.scriptengine.groovy.GroovyScriptEngine.<init>(GroovyScriptEngine.java:71)
	at net.grinder.scriptengine.groovy.GroovyScriptEngineService.createScriptEngine(GroovyScriptEngineService.java:109)
	at net.grinder.engine.process.ScriptEngineContainer.getScriptEngine(ScriptEngineContainer.java:105)
	at net.grinder.engine.process.GrinderProcess.run(GrinderProcess.java:330)
	at net.grinder.engine.process.WorkerProcessEntryPoint.run(WorkerProcessEntryPoint.java:87)
	at net.grinder.engine.process.WorkerProcessEntryPoint.main(WorkerProcessEntryPoint.java:60)
Caused by: net.grinder.scriptengine.groovy.GroovyScriptEngine$GroovyScriptExecutionException: Exception occurs in @BeforeProcess block.
	at net.grinder.scriptengine.groovy.GrinderContextExecutor.runBeforeProcess(GrinderContextExecutor.java:88)
	at net.grinder.scriptengine.groovy.GroovyScriptEngine.<init>(GroovyScriptEngine.java:64)
	... 5 common frames omitted
Caused by: java.lang.UnsupportedOperationException: null
	at java.util.Collections$UnmodifiableCollection.addAll(Collections.java:1065)
	at net.grinder.scriptengine.groovy.junit.GrinderRunner.withBeforeProcess(GrinderRunner.java:268)
	at net.grinder.scriptengine.groovy.GrinderContextExecutor.runBeforeProcess(GrinderContextExecutor.java:85)
	... 6 common frames omitted

2018-08-15 10:43:11,252 ERROR worker-bootstrap: Error running worker process
net.grinder.engine.common.EngineException: Error while initialize test runner
	at net.grinder.scriptengine.groovy.GroovyScriptEngine.<init>(GroovyScriptEngine.java:71)
	at net.grinder.scriptengine.groovy.GroovyScriptEngineService.createScriptEngine(GroovyScriptEngineService.java:109)
	at net.grinder.engine.process.ScriptEngineContainer.getScriptEngine(ScriptEngineContainer.java:105)
	at net.grinder.engine.process.GrinderProcess.run(GrinderProcess.java:330)
	at net.grinder.engine.process.WorkerProcessEntryPoint.run(WorkerProcessEntryPoint.java:87)
	at net.grinder.engine.process.WorkerProcessEntryPoint.main(WorkerProcessEntryPoint.java:60)
Caused by: net.grinder.scriptengine.groovy.GroovyScriptEngine$GroovyScriptExecutionException: Exception occurs in @BeforeProcess block.
	at net.grinder.scriptengine.groovy.GrinderContextExecutor.runBeforeProcess(GrinderContextExecutor.java:88)
	at net.grinder.scriptengine.groovy.GroovyScriptEngine.<init>(GroovyScriptEngine.java:64)
	... 5 common frames omitted
Caused by: java.lang.UnsupportedOperationException: null
	at java.util.Collections$UnmodifiableCollection.addAll(Collections.java:1065)
	at net.grinder.scriptengine.groovy.junit.GrinderRunner.withBeforeProcess(GrinderRunner.java:268)
	at net.grinder.scriptengine.groovy.GrinderContextExecutor.runBeforeProcess(GrinderContextExecutor.java:85)
	... 6 common frames omitted

**Comment by keny16888** [comment]
环境是jdk 1.8版本。

**Comment by junoyoon** [comment]
It's because you may mistakenly include JUnit in your pom.xml
nGrinder highly coupled with JUnit 4.8. If you include the other JUnit version, please downgrade it to 4.8.

**Comment by imbyungjun** [comment]
From nGrinder 3.5.4, there is no more JUnit 4.8 dependency. This issue will not be occurred anymore.
