### ISSUE TITLE
When requesting the interface of the https protocol, an error is reported: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

### ISSUE THREAD

**Issue by chkch** [naver/ngrinder#404]
@donggyu04 
Specific error message:
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_212]
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154) ~[na:1.8.0_212]
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2020) ~[na:1.8.0_212]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1127) ~[na:1.8.0_212]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367) ~[na:1.8.0_212]
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:750) ~[na:1.8.0_212]
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123) ~[na:1.8.0_212]
	at java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:167) ~[na:1.8.0_212]
	at HTTPClient.HTTPConnection.sendRequest(HTTPConnection.java:3148) ~[grinder-httpclient-3.11.jar:na]
	at HTTPClient.HTTPConnection.handleRequest(HTTPConnection.java:2884) ~[grinder-httpclient-3.11.jar:na]
	at HTTPClient.HTTPConnection.setupRequest(HTTPConnection.java:2676) ~[grinder-httpclient-3.11.jar:na]
	at HTTPClient.HTTPConnection.Post(HTTPConnection.java:1178) ~[grinder-httpclient-3.11.jar:na]
	at HTTPClient.HTTPConnection.Post(HTTPConnection.java:1143) ~[grinder-httpclient-3.11.jar:na]
	at HTTPClient.HTTPConnection.Post(HTTPConnection.java:1101) ~[grinder-httpclient-3.11.jar:na]
	at net.grinder.plugin.http.HTTPRequest$6.doRequest(HTTPRequest.java:816) ~[grinder-http-3.11.jar:na]
	at net.grinder.plugin.http.HTTPRequest$AbstractRequest.getHTTPResponse(HTTPRequest.java:1278) ~[grinder-http-3.11.jar:na]
	at net.grinder.plugin.http.HTTPRequest.POST(HTTPRequest.java:811) ~[grinder-http-3.11.jar:na]
	at net.grinder.plugin.http.HTTPRequest.POST(HTTPRequest.java:756) ~[grinder-http-3.11.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:188) ~[jython.jar:na]
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:206) ~[jython.jar:na]
	at org.python.core.PyObject.__call__(PyObject.java:497) ~[jython.jar:na]
	at org.python.core.PyObject.__call__(PyObject.java:501) ~[jython.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:141) ~[jython.jar:na]
	at org.python.pycode._pyx1.req$2(E:/Data/eclipse/PerfScripts/Test/111.py:40) ~[na:na]
	at org.python.pycode._pyx1.call_function(E:/Data/eclipse/PerfScripts/Test/111.py) ~[na:na]
	at org.python.core.PyTableCode.call(PyTableCode.java:171) ~[jython.jar:na]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:139) ~[jython.jar:na]
	at org.python.core.PyFunction.__call__(PyFunction.java:413) ~[jython.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:126) ~[jython.jar:na]
	at org.python.pycode._pyx1.__call__$3(E:/Data/eclipse/PerfScripts/Test/111.py:46) ~[na:na]
	at org.python.pycode._pyx1.call_function(E:/Data/eclipse/PerfScripts/Test/111.py) ~[na:na]
	at org.python.core.PyTableCode.call(PyTableCode.java:171) ~[jython.jar:na]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:308) ~[jython.jar:na]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:199) ~[jython.jar:na]
	at org.python.core.PyFunction.__call__(PyFunction.java:482) ~[jython.jar:na]
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237) ~[jython.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:228) ~[jython.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:223) ~[jython.jar:na]
	at org.python.core.PyObject.invoke(PyObject.java:3697) ~[jython.jar:na]
	at org.python.core.PyInstance.instance___call__(PyInstance.java:377) ~[jython.jar:na]
	at org.python.core.PyInstance.__call__(PyInstance.java:372) ~[jython.jar:na]
	at org.python.core.PyObject.__call__(PyObject.java:464) ~[jython.jar:na]
	at net.grinder.scriptengine.jython.JythonScriptEngine$JythonWorkerRunnable.run(JythonScriptEngine.java:263) ~[grinder-core-3.11.jar:na]
	at net.grinder.engine.process.GrinderThread.run(GrinderThread.java:119) ~[grinder-core-3.11.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]

**Comment by donggyu04** [comment]
@chkch 

Could you add `https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient` lib and 
use them instead of `net.grinder.plugin.http.*` in your test function?

**Comment by chkch** [comment]
Sorry, I am not very familiar with the java language and httpclient. It is difficult for me to use them.
Of course, I hope to get support and solve https performance and error issues in the new version.

**Comment by chkch** [comment]
The problem was found. It turned out that the domain name https of the tested service was configured with multiple certificates. I chose to bypass the proxy layer and directly request the service, but I still hope that the httpclient can be updated/resolved in the new version. Thank you @donggyu04
