### ISSUE TITLE
Duplicate Keys not allowed. Duplicate for 'class net.grinder.scriptengine.groovy.GroovyScriptEngineService

### ISSUE THREAD

**Issue by cmcccc** [naver/ngrinder#415]
2019-06-22 15:16:41,868 ERROR worker-bootstrap: Error running worker process
org.picocontainer.PicoCompositionException: Duplicate Keys not allowed. Duplicate for 'class net.grinder.scriptengine.groovy.GroovyScriptEngineService'
        at org.picocontainer.DefaultPicoContainer.addAdapterInternal(DefaultPicoContainer.java:438) ~[picocontainer-2.13.6.jar:na]
        at org.picocontainer.DefaultPicoContainer.addComponent(DefaultPicoContainer.java:548) ~[picocontainer-2.13.6.jar:na]
        at org.picocontainer.DefaultPicoContainer.addComponent(DefaultPicoContainer.java:501) ~[picocontainer-2.13.6.jar:na]
        at org.picocontainer.DefaultPicoContainer.addComponent(DefaultPicoContainer.java:488) ~[picocontainer-2.13.6.jar:na]
        at net.grinder.engine.process.ScriptEngineContainer.<init>(ScriptEngineContainer.java:84) ~[grinder-core-3.9.1.jar:na]
        at net.grinder.engine.process.GrinderProcess.run(GrinderProcess.java:290) ~[ngrinder-runtime-3.4.1-SNAPSHOT.jar:na]
        at net.grinder.engine.process.WorkerProcessEntryPoint.run(WorkerProcessEntryPoint.java:87) [grinder-core-3.9.1.jar:na]
        at net.grinder.engine.process.WorkerProcessEntryPoint.main(WorkerProcessEntryPoint.java:60) [grinder-core-3.9.1.jar:na]
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0

**Comment by junoyoon** [comment]
This issue does not have information we can dignose.
I'll close this issue now.
