### ISSUE TITLE
ngrinder 에이전트 다운로드 에러

### ISSUE THREAD

**Issue by Leekyungun** [naver/ngrinder#446]
## 상황
windows에 ngrinder를 설치하여 부하테스트를 하고자 합니다.
설치 후 admin 계정으로 로그인까지는 완료하였으나 
agent 다운로드시 에러가 발생합니다. 

## 버전
windows 10 버전 1809(OS 빌드 17763.615)
java - jdk1.8.0_221
ngrinder - 3.4.3 (2019.07.09)

## 설치 과정
1. java 설치 1.8 jdk
   - ```
      C:\Users\lku>java -version
      java version "1.8.0_221"
      Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
      Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

      C:\Users\lku>javac
      Usage: javac <options> <source files>
      where possible options include:
        -g                         Generate all debugging info
        -g:none                    Generate no debugging info
        -g:{lines,vars,source}     Generate only some debugging info
        ...
      ```
1. ngrinder 다운로드
   - [3.4.3 (2019.07.09)](https://github.com/naver/ngrinder/releases)
1. ngrinder 실행
   - `java -XX:MaxPermSize=200m -jar .\ngrinder-controller-3.4.3.war`
1. 로그인
   - admin/admin
1. agent 다운로드


## agent 다운로드시 페이지에 나오는 에러코드
```
HTTP ERROR 500
Problem accessing /agent/download. Reason:

    Server Error
Caused by:
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: No authentication
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:980)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:859)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:844)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	
        ...
 
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: No authentication
...
```

**Comment by donggyu04** [comment]
@Leekyungun 

안녕하세요.
저희가 문제 재현을 시도하고 있는데 문의 주신 스텝으로 똑같이 진행 하여도 문제 재현이 안되네요..

몇가지 정보를 더 여쭙고자 합니다.

1. 에이전트 다운로드 하실때 호출 하신 URL이 어떻게 되시나요?
2. 에이전트 다운로드는 auth가 필요 없습니다.(로그인과 무관) 고로 controller를 실행시키시고 
'localhost:8080/agent/download' 를 브라우저에 입력해보실 수 있으신가요?

**Comment by Leekyungun** [comment]
1. 에이전트 다운로드 하실때 호출 하신 URL이 어떻게 되시나요?
   - http://localhost:8080/agent/download
1. 에이전트 다운로드는 auth가 필요 없습니다.(로그인과 무관) 고로 controller를 실행시키시고
'localhost:8080/agent/download' 를 브라우저에 입력해보실 수 있으신가요?
   - 프로그램을 다시 시작한 뒤 브라우져 시크릿모드로 해당 URL 에 들어가면 같은 에러가 표시됩니다. 

=> 리눅스에 설치해보니 정상적으로 작동이 되었고 다른 윈도우 컴퓨터에도 설치해보고 있습니다.   

추가 질문. 
1. script - jython 모드를 사용할 때 json 모듈이나 request 모듈을 사용할 수 있나요?

**Comment by Leekyungun** [comment]
다른 윈도우 컴퓨터에도 정상작동하는것 확인하였습니다. 

첫번째 설치했던 윈도우 프로그램은 사용자 이름이 한글이라 다른 프로그램도 정상작동하지 않는것이 많은데 그거의 영향인게 아닌가하고 조심스럽게 추측해봅니다. 

```
2019-08-13 16:10:16,871 INFO  PostProcessorRegistrationDelegate.java:328 : Bean 'myExecutor' of type [class org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-08-13 16:10:17,199 INFO  Config.java:127 : nGrinder is starting...
2019-08-13 16:10:17,201 INFO  Config.java:353 : nGrinder home directory:C:\Users\한글\.ngrinder.
2019-08-13 16:10:17,202 INFO  Config.java:384 : nGrinder ex home directory:C:\Users\한글\.ngrinder_ex.
INFO 19. 8. 13 오후 4:10:liquibase: Reading from DATABASECHANGELOG
INFO 19. 8. 13 오후 4:10:liquibase: Reading from DATABASECHANGELOG
2019-08-13 16:10:23.266:INFO:/:main: Initializing Spring FrameworkServlet 'appServlet'
2019-08-13 16:10:23.984:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@5b59c3d{/,file:/C:/Users/%EC%9D%B4%EA%B2%BD%EC%96%B8/.ngrinder/tmp/webapp/,AVAILABLE}{file:/C:/ngrinder-controller-3.4.3.war}
2019-08-13 16:10:24.003:INFO:oejs.ServerConnector:main: Started ServerConnector@63dabddf{HTTP/1.1}{0.0.0.0:8080}
2019-08-13 16:10:24.004:INFO:oejs.Server:main: Started @31682ms
```

**Comment by imbyungjun** [comment]
@Leekyungun 

현재 nGrinder는 jython 2.5 버전만 지원하기 때문에 json 모듈을 import 하는 것은 불가능합니다. JSON 파싱에 관련한 가이드는 아래 링크에 정리되어있습니다.
https://github.com/naver/ngrinder/wiki/How-to-parse-JSON

request 모듈도 import 불가능합니다. HTTP 요청을 보내기 위해서는 jython 스크립트 생성 시 기본으로 import 하는 HttpRequest를 사용하실 수 있습니다.

**Comment by Leekyungun** [comment]
감사합니다 ^^ 
오늘하루도 수고하셨습니다~
