### ISSUE TITLE
not found dependencies.txt

### ISSUE THREAD

**Issue by xiaoyutongxue** [naver/ngrinder#538]
2020-04-13 15:48:10,258 ERROR AgentPackageService.java:319 : Error while loading dependencies.txt
java.lang.NullPointerException: null
	at java.io.Reader.<init>(Reader.java:78) ~[na:1.8.0_232]
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72) ~[na:1.8.0_232]
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1286) ~[commons-io-2.0.1.jar:2.0.1]
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:502) ~[commons-io-2.0.1.jar:2.0.1]

![image](https://user-images.githubusercontent.com/5894752/79104268-d03b2d80-7da0-11ea-8a6d-629ae9865ad7.png)

**Comment by donggyu04** [comment]
@xiaoyutongxue 

Build and run using IDEA not working some feature such as `download agent`
you must build with gradle (`gradlew `clean build -x test) and run created war.
`java -jar ngrinder-controller.war`

> war is located in `ngriner-controller/build/lib`
