### ISSUE TITLE
All workers are finished    but script error 

### ISSUE THREAD

**Issue by renhongchao** [naver/ngrinder#582]
version 3.4.2

2020-06-17 18:04:02,591 INFO  agent daemon  :  All workers are finished
2020-06-17 18:04:02,653 INFO  agent daemon  :  communication shut down

![image](https://user-images.githubusercontent.com/3937985/84885972-59831f00-b0c6-11ea-9032-6da6eb119533.png)

**Comment by donggyu04** [comment]
@renhongchao 

Could you attach all agent logs?

**Comment by renhongchao** [comment]
> @renhongchao
> 
> Could you attach all agent logs and your test scripts?

[agent.log](https://github.com/naver/ngrinder/files/4792537/agent.log)

[baidu.groovy.txt](https://github.com/naver/ngrinder/files/4792538/baidu.groovy.txt)


test cannot shutdown , show  Script error

**Comment by renhongchao** [comment]
and what cause the EngineException 

2020-06-17 20:34:39,030 ERROR agent daemon  :  Exception occurred in the agent message loop
net.grinder.engine.common.EngineException: Failed to send initialisation message

**Comment by renhongchao** [comment]
> @renhongchao
> 
> Could you attach all agent logs and your test scripts?

very sorry  the reason is when i modify  ngrinder-core agent jvmArguments XX:PermSize to java 8 XX:MetaspaceSize has a word mistaken     the agent daemon  :  Worker process  only show once EngineException

log




2020-06-17 20:34:38,880 INFO  agent daemon  :  Worker process command line: java '-javaagent:../../../../approot/compressed/ngrinder-agent/lib/grinder-dcr-agent-3.9.1.jar' '-Djna.library.path=/home/appops/.ngrinder_agent/file-store/admin/current/lib' '-Dpython.path=/home/appops/.ngrinder_agent/file-store/admin/current/lib' '-Dpython.cachedir=/tmp/jython' '-Dngrinder.etc.hosts=computron-agent-docker-cm-online-3-a7ol9-pggbz-7b58fd54d4-96wwk:127.0.0.1,localhost:127.0.0.1,' '-Dsun.net.spi.nameservice.provider.1=dns,LocalManagedDns' '-Duser.dir=/home/appops/.ngrinder_agent/file-store/admin/current' '-Dngrinder.context=agent' '-Xms2048m' '-Xmx2048m' '-XX:MetaSpace=128m' '-XX:MaxMetaSpace=128m' -classpath '../../../../approot/compressed/ngrinder-agent/lib/ngrinder-runtime-3.4.2.jar:../../../../approot/compressed/ngrinder-agent/lib/grinder-patch-3.9.1-patch.jar:.:../../../../approot/compressed/ngrinder-agent/lib/grinder-http-3.9.1.jar:../../../../approot/compressed/ngrinder-agent/lib/dnsjava-2.1.1.jar:../../../../approot/compressed/ngrinder-agent/lib/commons-lang-2.6.jar:../../../../approot/compressed/ngrinder-agent/lib/logback-core-1.0.0.jar:../../../../approot/compressed/ngrinder-agent/lib/junit-dep-4.8.2.jar:../../../../approot/compressed/ngrinder-agent/lib/grinder-core-3.9.1.jar:../../../../approot/compressed/ngrinder-agent/lib/logback-classic-1.0.0.jar:../../../../approot/compressed/ngrinder-agent/lib/slf4j-api-1.6.4.jar:../../../../approot/compressed/ngrinder-agent/lib/commons-io-2.0.1.jar:../../../../approot/compressed/ngrinder-agent/lib/grinder-dcr-agent-3.9.1.jar:../../../../approot/compressed/ngrinder-agent/lib/asm-3.3.1.jar:../../../../approot/compressed/ngrinder-agent/lib/ngrinder-groovy-3.4.2.jar:../../../../approot/compressed/ngrinder-agent/lib/picocontainer-2.13.6.jar:../../../../approot/compressed/ngrinder-agent/lib/groovy-all-2.2.1.jar:../../../../approot/compressed/ngrinder-agent/lib/grinder-httpclient-3.9.1.jar:../../../../approot/compressed/ngrinder-agent/lib/json-20090211.jar:../../../../approot/compressed/ngrinder-agent/lib/hamcrest-all-1.1.jar:../../../../approot/compressed/ngrinder-agent/lib/ngrinder-runtime-3.4.2.jar' net.grinder.engine.process.WorkerProcessEntryPoint
2020-06-17 20:34:39,030 ERROR agent daemon  :  Exception occurred in the agent message loop
net.grinder.engine.common.EngineException: Failed to send initialisation message
        at net.grinder.engine.agent.AbstractWorkerFactory.create(AbstractWorkerFactory.java:92) ~[grinder-core-3.9.1.jar:na]
        at net.grinder.engine.agent.WorkerLauncher.startSomeWorkers(WorkerLauncher.java:103) ~[grinder-core-3.9.1.jar:na]
        at net.grinder.engine.agent.WorkerLauncher.startAllWorkers(WorkerLauncher.java:91) ~[grinder-core-3.9.1.jar:na]
        at net.grinder.engine.agent.AgentImplementationEx.run(AgentImplementationEx.java:272) ~[ngrinder-core-3.4.2.jar:na]
        at net.grinder.AgentDaemon$AgentThreadRunnable.run(AgentDaemon.java:132) [ngrinder-core-3.4.2.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
Caused by: net.grinder.communication.CommunicationException: Exception whilst sending message
        at net.grinder.communication.AbstractSender.send(AbstractSender.java:57) ~[grinder-core-3.9.1.jar:na]
        at net.grinder.engine.agent.AbstractWorkerFactory.create(AbstractWorkerFactory.java:88) ~[grinder-core-3.9.1.jar:na]
        ... 5 common frames omitted
Caused by: java.io.IOException: Broken pipe
        at java.io.FileOutputStream.writeBytes(Native Method) ~[na:1.8.0_101]
        at java.io.FileOutputStream.write(FileOutputStream.java:326) ~[na:1.8.0_101]
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[na:1.8.0_101]
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[na:1.8.0_101]
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:141) ~[na:1.8.0_101]
        at java.io.ObjectOutputStream$BlockDataOutputStream.flush(ObjectOutputStream.java:1823) ~[na:1.8.0_101]
        at java.io.ObjectOutputStream.flush(ObjectOutputStream.java:719) ~[na:1.8.0_101]
        at net.grinder.communication.AbstractSender.writeMessageToStream(AbstractSender.java:90) ~[grinder-core-3.9.1.jar:na]
        at net.grinder.communication.StreamSender.writeMessage(StreamSender.java:70) ~[grinder-core-3.9.1.jar:na]
        at net.grinder.communication.AbstractSender.send(AbstractSender.java:53) ~[grinder-core-3.9.1.jar:na]
        ... 6 common frames omitted
2020-06-17 20:34:39,034 INFO  agent daemon  :  communication shut down
2020-06-17 20:34:39,034 INFO  agent daemon  :  Test shuts down.
2020-06-17 20:34:39,035 INFO  agent controller  :  Send log for test_144
2020-06-17 20:34:39,051 INFO  agent controller  :  Clean up the perftest logs













2020-06-17 20:38:52,058 INFO  agent daemon  :  Worker process command line: java '-javaagent:../../../../approot/compressed/ngrinder-agent/lib/grinder-dcr-agent-3.9.1.jar' '-Djna.library.path=/home/appops/.ngrinder_agent/file-store/admin/current/lib' '-Dpython.path=/home/appops/.ngrinder_agent/file-store/admin/current/lib' '-Dpython.cachedir=/tmp/jython' '-Dngrinder.etc.hosts=computron-agent-docker-cm-online-3-a7ol9-pggbz-7b58fd54d4-96wwk:127.0.0.1,localhost:127.0.0.1,' '-Dsun.net.spi.nameservice.provider.1=dns,LocalManagedDns' '-Duser.dir=/home/appops/.ngrinder_agent/file-store/admin/current' '-Dngrinder.context=agent' '-Xms2048m' '-Xmx2048m' '-XX:MetaSpace=128m' '-XX:MaxMetaSpace=128m' -classpath '../../../../approot/compressed/ngrinder-agent/lib/ngrinder-runtime-3.4.2.jar:../../../../approot/compressed/ngrinder-agent/lib/grinder-patch-3.9.1-patch.jar:.:../../../../approot/compressed/ngrinder-agent/lib/grinder-http-3.9.1.jar:../../../../approot/compressed/ngrinder-agent/lib/dnsjava-2.1.1.jar:../../../../approot/compressed/ngrinder-agent/lib/commons-lang-2.6.jar:../../../../approot/compressed/ngrinder-agent/lib/logback-core-1.0.0.jar:../../../../approot/compressed/ngrinder-agent/lib/junit-dep-4.8.2.jar:../../../../approot/compressed/ngrinder-agent/lib/grinder-core-3.9.1.jar:../../../../approot/compressed/ngrinder-agent/lib/logback-classic-1.0.0.jar:../../../../approot/compressed/ngrinder-agent/lib/slf4j-api-1.6.4.jar:../../../../approot/compressed/ngrinder-agent/lib/commons-io-2.0.1.jar:../../../../approot/compressed/ngrinder-agent/lib/grinder-dcr-agent-3.9.1.jar:../../../../approot/compressed/ngrinder-agent/lib/asm-3.3.1.jar:../../../../approot/compressed/ngrinder-agent/lib/ngrinder-groovy-3.4.2.jar:../../../../approot/compressed/ngrinder-agent/lib/picocontainer-2.13.6.jar:../../../../approot/compressed/ngrinder-agent/lib/groovy-all-2.2.1.jar:../../../../approot/compressed/ngrinder-agent/lib/grinder-httpclient-3.9.1.jar:../../../../approot/compressed/ngrinder-agent/lib/json-20090211.jar:../../../../approot/compressed/ngrinder-agent/lib/hamcrest-all-1.1.jar:../../../../approot/compressed/ngrinder-agent/lib/ngrinder-runtime-3.4.2.jar' net.grinder.engine.process.WorkerProcessEntryPoint
2020-06-17 20:38:52,063 INFO  agent daemon  :  worker computron-agent-docker-cm-online-3-a7ol9-pggbz-7b58fd54d4-96wwk-0 started
2020-06-17 20:38:52,065 INFO  agent daemon  :  All workers are finished
2020-06-17 20:38:52,066 INFO  agent daemon  :  communication shut down
2020-06-17 20:38:52,124 INFO  agent daemon  :  Test shuts down.
2020-06-17 20:38:52,125 INFO  agent controller  :  Send log for test_145
2020-06-17 20:38:52,125 INFO  agent controller  :  Clean up the perftest logs
