### ISSUE TITLE
After shutdown.sh, I can not start normally

### ISSUE THREAD

**Issue by parkjunhyo** [naver/ngrinder#674]
I ran this on Ubuntu. 

# java --version
openjdk 11.0.8 2020-07-14

# Tomcat
apache-tomcat-9.0.39.tar.gz

# ngrinder 
: ngrinder-3.5.2
: ngrinder-3.5.1
: ngrinder-3.4.2  

After first starup.sh, there are no problem, However, after shutdown.sh and second starup.sh
I can not start these, 3.5.1 and 3.5.2 (3.4.2 is fine)

The below came from "logs/catalina.out" file
Is there something missed? Please let me know.

2020-10-16 06:06:11,278 INFO  StartupInfoLogger.java:55 : Starting NGrinderControllerStarter v3.5.1 on tidcne-admin-0 with PID 11268 (/opt/tomcat/webapps/ngrinder-controller-3.5.1/WEB-INF/classes started by root in /opt/tomcat)
2020-10-16 06:06:11,280 INFO  SpringApplication.java:655 : The following profiles are active: production
2020-10-16 06:06:11,971 INFO  RepositoryConfigurationDelegate.java:127 : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2020-10-16 06:06:12,065 INFO  RepositoryConfigurationDelegate.java:187 : Finished Spring Data repository scanning in 86ms. Found 5 JPA repository interfaces.
2020-10-16 06:06:12,591 INFO  PostProcessorRegistrationDelegate.java:335 : Bean 'taskConfig' of type [org.ngrinder.infra.config.TaskConfig$$EnhancerBySpringCGLIB$$743de473] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-10-16 06:06:12,890 INFO  Config.java:122 : nGrinder is starting...
2020-10-16 06:06:12,892 INFO  Config.java:334 : nGrinder ex home directory:/root/.ngrinder_ex.
2020-10-16 06:06:12,970 INFO  ServletWebServerApplicationContext.java:285 : Root WebApplicationContext: initialization completed in 1478 ms
2020-10-16 06:06:13,116 INFO  DefaultPluginStatusProvider.java:49 : Enabled plugins: []
2020-10-16 06:06:13,116 INFO  DefaultPluginStatusProvider.java:53 : Disabled plugins: []
2020-10-16 06:06:13,119 INFO  DefaultPluginManager.java:110 : PF4J version 3.0.1 in 'deployment' mode
2020-10-16 06:06:13,131 INFO  AbstractPluginManager.java:215 : No plugins
2020-10-16 06:06:13,229 INFO  DynamicRegistrationBean.java:110 : Filter formContentFilter was not registered (possibly already registered?)
2020-10-16 06:06:13,230 INFO  DynamicRegistrationBean.java:110 : Filter pluggableServletFilter was not registered (possibly already registered?)
2020-10-16 06:06:13,508 WARN  AbstractApplicationContext.java:559 : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'databaseUpdater': Invocation of init method failed; nested exception is org.ngrinder.common.exception.NGrinderRuntimeException: Error getting database from jdbc:h2:/root/.ngrinder/db/h2
2020-10-16 06:06:13,520 INFO  ConditionEvaluationReportLoggingListener.java:136 : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-10-16 06:06:13,524 ERROR SpringApplication.java:837 : Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'databaseUpdater': Invocation of init method failed; nested exception is org.ngrinder.common.exception.NGrinderRuntimeException: Error getting database from jdbc:h2:/root/.ngrinder/db/h2
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:415)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:311)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1109)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:173)
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:153)
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:95)
        at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:172)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5166)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:706)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1848)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
        at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:773)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:843)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
Caused by: org.ngrinder.common.exception.NGrinderRuntimeException: Error getting database from jdbc:h2:/root/.ngrinder/db/h2
        at org.ngrinder.common.util.ExceptionUtils.processException(ExceptionUtils.java:53)
        at org.ngrinder.infra.init.DatabaseUpdater.getDatabase(DatabaseUpdater.java:57)
        at org.ngrinder.infra.init.DatabaseUpdater.init(DatabaseUpdater.java:76)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
        ... 62 common frames omitted
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-197])
        at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549)
        at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
        at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
        at org.ngrinder.infra.init.DatabaseUpdater.getDatabase(DatabaseUpdater.java:55)
        at org.ngrinder.infra.init.DatabaseUpdater.init(DatabaseUpdater.java:76)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Caused by: org.h2.jdbc.JdbcSQLException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-197]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
        at org.h2.message.DbException.get(DbException.java:168)
        at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:188)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:168)
        at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
        at org.h2.engine.Database.getPageStore(Database.java:2538)
        at org.h2.engine.Database.open(Database.java:709)
        at org.h2.engine.Database.openDatabase(Database.java:286)
        at org.h2.engine.Database.<init>(Database.java:280)
        at org.h2.engine.Engine.openSession(Engine.java:66)
        at org.h2.engine.Engine.openSession(Engine.java:179)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
        at org.h2.engine.Engine.createSession(Engine.java:140)
        at org.h2.engine.Engine.createSession(Engine.java:28)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
        at org.h2.Driver.connect(Driver.java:69)
        at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
        at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
        at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556)
        at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
        ... 12 common frames omitted
Caused by: java.lang.IllegalStateException: The file is locked: nio:/root/.ngrinder/db/h2.mv.db [1.4.197/7]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:870)
        at org.h2.mvstore.FileStore.open(FileStore.java:173)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:350)
        at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2934)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
        ... 30 common frames omitted
16-Oct-2020 06:06:13.526 SEVERE [main] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive [/opt/tomcat/webapps/ngrinder-controller-3.5.1.war]
        java.lang.IllegalStateException: Error starting child
                at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:720)
                at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
                at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:706)
                at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
                at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1848)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
                at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
                at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:773)
                at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427)
                at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
                at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
                at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
                at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
                at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
                at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:843)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
                at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
                at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
        Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/ngrinder-controller-3.5.1]]
                at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
                at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
                ... 37 more
        Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'databaseUpdater': Invocation of init method failed; nested exception is org.ngrinder.common.exception.NGrinderRuntimeException: Error getting database from jdbc:h2:/root/.ngrinder/db/h2
                at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:415)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
                at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
                at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
                at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
                at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
                at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:311)
                at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
                at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1109)
                at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
                at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
                at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
                at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
                at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
                at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
                at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
                at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:173)
                at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:153)
                at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:95)
                at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:172)
                at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5166)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                ... 38 more
        Caused by: org.ngrinder.common.exception.NGrinderRuntimeException: Error getting database from jdbc:h2:/root/.ngrinder/db/h2
                at org.ngrinder.common.util.ExceptionUtils.processException(ExceptionUtils.java:53)
                at org.ngrinder.infra.init.DatabaseUpdater.getDatabase(DatabaseUpdater.java:57)
                at org.ngrinder.infra.init.DatabaseUpdater.init(DatabaseUpdater.java:76)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
                at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
                at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
                ... 62 more
        Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-197])
                at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549)
                at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
                at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
                at org.ngrinder.infra.init.DatabaseUpdater.getDatabase(DatabaseUpdater.java:55)
                at org.ngrinder.infra.init.DatabaseUpdater.init(DatabaseUpdater.java:76)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
                at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        Caused by: org.h2.jdbc.JdbcSQLException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-197]
                at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
                at org.h2.message.DbException.get(DbException.java:168)
                at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:188)
                at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:168)
                at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
                at org.h2.engine.Database.getPageStore(Database.java:2538)
                at org.h2.engine.Database.open(Database.java:709)
                at org.h2.engine.Database.openDatabase(Database.java:286)
                at org.h2.engine.Database.<init>(Database.java:280)
                at org.h2.engine.Engine.openSession(Engine.java:66)
                at org.h2.engine.Engine.openSession(Engine.java:179)
                at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
                at org.h2.engine.Engine.createSession(Engine.java:140)
                at org.h2.engine.Engine.createSession(Engine.java:28)
                at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
                at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
                at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
                at org.h2.Driver.connect(Driver.java:69)
                at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
                at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
                at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556)
                at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
                ... 12 more
        Caused by: java.lang.IllegalStateException: The file is locked: nio:/root/.ngrinder/db/h2.mv.db [1.4.197/7]
                at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:870)
                at org.h2.mvstore.FileStore.open(FileStore.java:173)
                at org.h2.mvstore.MVStore.<init>(MVStore.java:350)
                at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2934)
                at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
                ... 30 more
16-Oct-2020 06:06:13.529 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/opt/tomcat/webapps/ngrinder-controller-3.5.1.war] has finished in [6,199] ms
16-Oct-2020 06:06:13.530 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/opt/tomcat/webapps/ngrinder-controller-3.5.2.war]
16-Oct-2020 06:06:16.669 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
06:06:16,687 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
06:06:16,687 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
06:06:16,687 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/opt/tomcat/webapps/ngrinder-controller-3.5.2/WEB-INF/classes/logback.xml]
06:06:16,688 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
06:06:16,688 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/opt/tomcat/webapps/ngrinder-controller-3.5.2/WEB-INF/classes/logback.xml]
06:06:16,688 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/opt/tomcat/webapps/ngrinder-controller-3.5.2/WEB-INF/lib/grinder-core-3.9.1.jar!/logback.xml]
06:06:16,707 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
06:06:16,708 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
06:06:16,709 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [console]
06:06:16,712 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
06:06:16,723 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.ngrinder.infra.logger.CoreLogger] to INFO
06:06:16,723 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.ngrinder.infra.logger.CoreLogger] to false
06:06:16,723 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [console] to Logger[org.ngrinder.infra.logger.CoreLogger]
06:06:16,723 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - ROOT level set to INFO
06:06:16,723 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [console] to Logger[ROOT]
06:06:16,723 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
06:06:16,723 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@5ce7af3f - Registering current configuration as safe fallback point

**Comment by donggyu04** [comment]
@parkjunhyo 

Thanks for your reports.
I will attempt to reproduction and fix that.

It seems a unterminated database connection problem.

Nevertheless, is 3.4.2 work well?

**Comment by parkjunhyo** [comment]
@donggyu04 

3.4.2 and 3.4.4 are fine. I hope that it will be fixed ASAP. Thanks

**Comment by junoyoon** [comment]
Sorry. The word ```ASAP``` is not appropriate in opensource project. :-)

**Comment by donggyu04** [comment]
@parkjunhyo 

Before update, You can use `java -jar ngrinder-controller-{version}.war` to run ngrinder without external WAS.
Try this, it might resolve your problem.

**Comment by parkjunhyo** [comment]
@donggyu04 

Thanks so much.

**Comment by silloy** [comment]
3.5.3 have the same question
