### ISSUE TITLE
ngrider3.5.4-Use mysql database to report NGrinderRuntimeException: Exception occurs while Liquibase update DB

### ISSUE THREAD

**Issue by jeff526** [naver/ngrinder#784]
### 1. Describe the bug 🐞 
:exclamation: DO NOT ASK QUESTION HERE PLEASE USE [DISCUSSION](https://github.com/naver/ngrinder/discussions) INSTEAD.

g.springframework.beans.factory.BeanCreationException: Error creating bean with name 'databaseUpdater': Invocation of init method failed; nested exception is org.ngrinder.common.exception.NGrinderRuntimeException: Exception occurs while Liquibase update DB
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:415)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:311)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1109)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at org.ngrinder.starter.NGrinderControllerStarter.main(NGrinderControllerStarter.java:261)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
Caused by: org.ngrinder.common.exception.NGrinderRuntimeException: Exception occurs while Liquibase update DB
        at org.ngrinder.common.util.ExceptionUtils.processException(ExceptionUtils.java:53)
        at org.ngrinder.infra.init.DatabaseUpdater.init(DatabaseUpdater.java:80)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
        ... 29 common frames omitted
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set ngrinder_datachange_logfile/db.changelog_schema_31.xml::31::ngrinder.3.5.3:
     Reason: liquibase.exception.DatabaseException: Unknown column 'created_date' in 'perf_test' [Failed SQL: ALTER TABLE ngrinderCluster.PERF_TEST CHANGE created_date created_at timestamp]
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:619)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:79)
        at liquibase.Liquibase.update(Liquibase.java:214)
        at liquibase.Liquibase.update(Liquibase.java:192)
        at liquibase.Liquibase.update(Liquibase.java:188)
        at liquibase.Liquibase.update(Liquibase.java:181)
        at org.ngrinder.infra.init.DatabaseUpdater.init(DatabaseUpdater.java:78)
        at org.ngrinder.starter.NGrinderControllerStarter.main(NGrinderControllerStarter.java:261)
Caused by: liquibase.exception.DatabaseException: Unknown column 'created_date' in 'perf_test' [Failed SQL: ALTER TABLE ngrinderCluster.PERF_TEST CHANGE created_date created_at timestamp]
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:309)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:113)
        at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1277)
        at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1259)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:582)
        ... 8 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'created_date' in 'perf_test'
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:782)
        at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:666)
        at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
        at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
        at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:307)
        ... 13 common frames omitted

### 3. Environment
- Controller
     - OS: cenos7.5
     - Browser:
     - JDK version:
     - Controller version:
- Agent
     - OS: 
     - JDK version:
     - Agent version:

### 4. Screenshots
If necessary, add screenshots to help explain your problem.

**Comment by donggyu04** [comment]
Hi.
What is your version of ngrinder before running 3.5.4?

**Comment by jeff526** [comment]
@donggyu04 3.5.0

**Comment by donggyu04** [comment]
@jeff526 

1. Could you attach your current `PERF_TEST` table schema? 'created_date' column does not exist?
2. What is the result of running `select * from DATABASECHANGELOG;` in your database?

**Comment by jeff526** [comment]
Run "select * from " result :

**Comment by jeff526** [comment]
"ID","AUTHOR","FILENAME","DATEEXECUTED","ORDEREXECUTED","EXECTYPE","MD5SUM","DESCRIPTION","COMMENTS","TAG","LIQUIBASE","CONTEXTS","LABELS","DEPLOYMENT_ID"
"2",initialDB,ngrinder_datachange_logfile/db.changelog_schema_MYSQL.xml,"2020-08-03 14:24:36.0",1,EXECUTED,"7:83ff87b1dcdf36c47bcf5e514a84e30d",sql,DB(MySQL) initialization.,,"3.5.3",,,"6435875959"
"29",ngrinder.3.5.1,ngrinder_datachange_logfile/db.changelog_schema_29.xml,"2021-03-24 14:18:34.0",2,EXECUTED,"7:cf0414911aa067d392c4b71682577b86","dropColumn columnName=mobile_phone, tableName=NUSER","",,"3.5.3",,,"6566714113"
"30",ngrinder.3.5.2,ngrinder_datachange_logfile/db.changelog_schema_30.xml,"2021-03-24 14:18:34.0",3,EXECUTED,"7:a4928c0299218b4436c1eef754d9b223",createTable tableName=WEBHOOK_CONFIG; createTable tableName=WEBHOOK_ACTIVATION,"",,"3.5.3",,,"6566714113"

**Comment by jeff526** [comment]
Steps to reproduce the above problem:
1. Put nGrinder3.5.4.war into Tomcat; it is possible to use the default H2 database;
2. Modify /root.ngrinder/database.conf to MySQL database;
3. Restart the Tomact service;
4. The above error log information will appear;

**Comment by jeff526** [comment]
@donggyu04  Is there a solution to this problem?

**Comment by junoyoon** [comment]
we will release the 3.5.5 version fixing this issue by the end of this month.
@jeff526

**Comment by donggyu04** [comment]
@junoyoon @jeff526 

This issue seems a little different. #788 is not happened in MySQL.

`Reason: liquibase.exception.DatabaseException: Unknown column 'created_date' in 'perf_test' `
`Unknown column 'created_date'` cannot occur in the normal case.

I will check again this phenomenon.

**Comment by donggyu04** [comment]
`Unknown column 'created_date` occurs in the process of Liquibase changing the column name `created_date` to `created_at`.

I don't understand why 'created_date` does not exist before updating.

**Comment by donggyu04** [comment]
@jeff526 

Could you add columns that show as `Unknown` manually?
You can check which column should exist before updating. check the `oldColumnName` in the file below.

https://github.com/naver/ngrinder/blob/develop/ngrinder-controller/src/main/resources/ngrinder_datachange_logfile/db.changelog_schema_31.xml

**Comment by jeff526** [comment]
> 我们将在本月底发布解决此问题的3.5.5版本。
> @ jeff526
> 
> 参见[＃788](https://github.com/naver/ngrinder/pull/788)

Thank you, looking forward to the new version

**Comment by jeff526** [comment]
> @ jeff526
> 
> 您可以添加显示为`Unknown`手动的列吗？
> 您可以在更新之前检查哪一列应该存在。检查`oldColumnName`下面的文件。
> 
> https://github.com/naver/ngrinder/blob/develop/ngrinder-controller/src/main/resources/ngrinder_datachange_logfile/db.changelog_schema_31.xml
Ok i take time to try
thankyou !
