### ISSUE TITLE
Some test annotation cause script initialized failed

### ISSUE THREAD

**Issue by yonger1516** [naver/ngrinder#88]
e.g. I add '@Repeat' annotation to groovy test class as following: 
@Repeat(2) 
@RunWith(GrinderRunner) 
class TestRunner { 

Then error message in agent log: 

2015-12-03 13:17:31,567 ERROR Script error - Error while initialize test runner 
net.grinder.engine.common.EngineException: Error while initialize test runner 
        at net.grinder.scriptengine.groovy.GroovyScriptEngine.<init>(GroovyScriptEngine.java:71) ~[ngrinder-groovy-3.3.1.jar:na] 
        at net.grinder.scriptengine.groovy.GroovyScriptEngineService.createScriptEngine(GroovyScriptEngineService.java:109) ~[ngrinder-groovy-3.3.1.jar:na] 
        at net.grinder.engine.process.ScriptEngineContainer.getScriptEngine(ScriptEngineContainer.java:105) ~[grinder-core-3.9.1.jar:na] 
        at net.grinder.engine.process.GrinderProcess.run(GrinderProcess.java:329) ~[ngrinder-runtime-3.3.1.jar:na] 
        at net.grinder.engine.process.WorkerProcessEntryPoint.run(WorkerProcessEntryPoint.java:87) [grinder-core-3.9.1.jar:na] 
        at net.grinder.engine.process.WorkerProcessEntryPoint.main(WorkerProcessEntryPoint.java:60) [grinder-core-3.9.1.jar:na] 
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed: 
${NGRINDER_HOME}\script\admin\baidu-firstpage.groovy: 30: unable to resolve class Repeat ,  unable to find class for annotation 
 @ line 30, column 1. 
   @Repeat(2) 
   ^ 

1 error

**Comment by yonger1516** [comment]
I think it is an issue,so copy it from google groups :http://ngrinder.642.n7.nabble.com/some-test-annotation-cause-script-initialized-failed-td1907.html

**Comment by yonger1516** [comment]
The error is also encountered when using "@RunRate(2)" annotation at method in groovy script,but such as "BeforeProcess" works well. Very confuse to me.

**Comment by junoyoon** [comment]
it seems that you didn't put the proper import statement.

```import net.grinder.scriptengine.groovy.junit.annotation.RunRate``` is necessary.
