### ISSUE TITLE
SSLHandshakeException occurs when requesting HTTPS POST

### ISSUE THREAD

**Issue by sileeee** [naver/ngrinder#914]
### 1. Describe the bug 🐞 

SSLHandshakeException occurred when requesting HTTPS POST. Even after updating ngrinder to the latest version, the error status remained. Our server does not support below TLS1.2, but request packet from HTTP Client exported from ngrinder seems to send a request to TLSv1 first. I would like to send a request by fixing the TLS version of HTTP Client to 1.2.

### 2. Reproduction steps
1. Prepare a server that supports only TLS1.2 or higher
2. Create a HTTPS POST test script.
3. Add `java.lang.System.setProperty("https.protocols", "TLSv1.2");` to the script.
4. Run the test.
5. See error.
```
2022-10-11 11:43:42,083 ERROR java.util.concurrent.ExecutionException: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at org.apache.hc.core5.reactor.ssl.SSLIOSession.doUnwrap(SSLIOSession.java:278)
        at org.apache.hc.core5.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:338)
        at org.apache.hc.core5.reactor.ssl.SSLIOSession.access$300(SSLIOSession.java:71)
        at org.apache.hc.core5.reactor.ssl.SSLIOSession$1.inputReady(SSLIOSession.java:175)
        at org.apache.hc.core5.reactor.InternalDataChannel.onIOEvent(InternalDataChannel.java:124)
        at org.apache.hc.core5.reactor.InternalChannel.handleIOEvent(InternalChannel.java:51)
        at org.apache.hc.core5.reactor.SingleCoreIOReactor.processEvents(SingleCoreIOReactor.java:179)
        at org.apache.hc.core5.reactor.SingleCoreIOReactor.doExecute(SingleCoreIOReactor.java:128)
        at org.apache.hc.core5.reactor.AbstractSingleCoreIOReactor.execute(AbstractSingleCoreIOReactor.java:85)
        at org.apache.hc.core5.reactor.IOReactorWorker.run(IOReactorWorker.java:44)
```

### 3. Environment
- Controller
     - OS: ubuntu-18.04
     - Browser: Chrome 106.0.5249.119
     - JDK version: 11.0.16
     - Controller version: 3.5.6
- Agent
     - OS: ubuntu-18.04
     - JDK version: 11.0.16
     - Agent version: 3.5.6

### 4. Screenshots
<img src="https://user-images.githubusercontent.com/31584255/195234265-631ab4fa-dd9d-4811-8518-0f10ebbc45f3.png" width="600"/>
<img src="https://user-images.githubusercontent.com/31584255/195234285-5833aa30-4c2a-4b21-a7e6-5c561580e59a.png" width="600"/>

**Comment by imbyungjun** [comment]
If the protocol is `HTTP/1.1`, HTTP client will handle TLS with [BasicClientTlsStrategy](https://github.com/apache/httpcomponents-core/blob/a1195d434a8083c58f0418bf625b0a6cf718a1c7/httpcore5/src/main/java/org/apache/hc/core5/http/nio/ssl/BasicClientTlsStrategy.java#L100),
and if the protocol is `HTTP/2.0`, HTTP client will handle TLS with [H2ClientTlsStrategy](https://github.com/apache/httpcomponents-core/blob/5.0.x/httpcore5-h2/src/main/java/org/apache/hc/core5/http2/ssl/H2ClientTlsStrategy.java#L104).
Both of them filters weak TLS  protocol version `TLSv1` and `TLSv1.1` by using [`TLS.excludeWeak()`](https://github.com/apache/httpcomponents-core/blob/5.0.x/httpcore5/src/main/java/org/apache/hc/core5/http/ssl/TLS.java#L87).

I don't understand that nGrinder HTTP client sends a request with `TLSv1`

**Comment by Newbie-HG** [comment]
same exception as this, how to fix it , please

**Comment by junoyoon** [comment]
@imbyungjun plz, check this.

**Comment by imbyungjun** [comment]
This error is not a bug or malfunction of nGrinder.

To handle this error, check this [question](https://stackoverflow.com/questions/6353849/received-fatal-alert-handshake-failure-through-sslhandshakeexception) for details.
And also see these links.
- https://www.baeldung.com/java-ssl-handshake-failures#1-missing-server-certificate
- https://stackoverflow.com/questions/33048172/ssl-handshake-failed-java-1-8

Simply, the first thing you can do is upgrade your JDK.
And the next thing is add your server's cert to client's trust store.
