### ISSUE TITLE
Performance test cannot be stopped

### ISSUE THREAD

**Issue by mashuangwei** [naver/ngrinder#933]
### 1. Describe the bug 🐞 
ngrinder-controller 3.5.7 version   centos7
There is no stop button on the page. It is stuck here all the time
![image](https://user-images.githubusercontent.com/7100779/198534975-6e52756b-67f0-4633-a91d-078bd902652d.png)

Clicking Stop has no effect, and the test cannot be stopped
![image](https://user-images.githubusercontent.com/7100779/198535430-27fc2157-2975-4446-96e0-3d4443e7107c.png)

### 4. Screenshots
If necessary, add screenshots to help explain your problem.

**Comment by imbyungjun** [comment]
Let me know the message shown when you hover the status icon.

**Comment by donggyu04** [comment]
@mashuangwei

Please attach your controller logs. there is no way to check your problem.

I recommend you to following process.

1. delete weird test (click checkbox  & click delete button)
2. restart controller
3. create new test and run

**Comment by mashuangwei** [comment]
> Let me know the message shown when you hover the status icon.

Status display stops

**Comment by mashuangwei** [comment]
> @mashuangwei
> 
> Please attach your controller logs. there is no way to check your problem. and I recommend you to following process.
> 
> 1. delete weird test (click checkbox  & click delete button)
> 2. restart controller
> 3. create new test and run

ok,  I'll try

**Comment by mashuangwei** [comment]
> @mashuangwei
> 
> Please attach your controller logs. there is no way to check your problem. and I recommend you to following process.
> 
> 1. delete weird test (click checkbox  & click delete button)
> 2. restart controller
> 3. create new test and run

There is no problem with script verification. After several rounds of testing, the test plan cannot be executed.controller logs: 

2022-10-31 13:34:59,472 INFO  Home.java:231 : /root/.ngrinder/perftest/0_999/138 is created.
2022-10-31 13:34:59,473 INFO  Home.java:231 : /root/.ngrinder/perftest/0_999/138/dist is created.
2022-10-31 13:34:59,478 INFO  PerfTestService.java:678 : [138][admin] Script type is 'groovy'.
2022-10-31 13:34:59,481 INFO  ScriptHandler.java:173 : [138][admin] msw/redis-sdk-get.groovy is being written in /root/.ngrinder/perftest/0_999/138/dist
2022-10-31 13:34:59,483 INFO  PerfTestService.java:683 : [138][admin] File write is completed in /root/.ngrinder/perftest/0_999/138/dist
2022-10-31 13:34:59,484 INFO  PerfTestService.java:638 : [138][admin] Grinder Properties : {grinder.threads=90, grinder.jvm.user.library.classpath=., grinder.numberOfOldLogs=1, grinder.test.id=test_138, grinder.duration=360000, grinder.sleepTimeVariation=0.2, grinder.runs=0, grinder.useConsole=true, grinder.script=redis-sdk-get.groovy, grinder.jvm=java, grinder.security=false, grinder.processIncrement=0, grinder.sleepTimeFactor=1, ngrinder.etc.hosts=, grinder.user=admin, grinder.connectionReset=true, grinder.reportTimesToConsole=true, grinder.debug.singleprocess=false, grinder.processes=1, grinder.security.level=normal, grinder.ignoreSampleCount=0, grinder.reportToConsole.interval=500, grinder.agents=2, grinder.dcrinstrumentation=true, grinder.logProcessStreams=true} 
2022-10-31 13:34:59,502 INFO  ConsoleFoundationEx.java:171 : console localhost:12000 has been started
2022-10-31 13:34:59,506 INFO  AgentService.java:380 : [138][admin] 2 agents are starting.
2022-10-31 13:34:59,506 INFO  AgentService.java:382 : [138][admin] - Agent TEST-DMZ-2210-V2108
2022-10-31 13:34:59,506 INFO  AgentService.java:382 : [138][admin] - Agent TEST-DMZ-2210-V2109
2022-10-31 13:34:59,510 INFO  AgentControllerServerDaemon.java:247 : Process 'TEST-DMZ-2210-V2108' [TEST-DMZ-2210-V2108:1906808037|1666772963744|-1673265866:0] agent is started.
2022-10-31 13:34:59,512 INFO  AgentControllerServerDaemon.java:247 : Process 'TEST-DMZ-2210-V2109' [TEST-DMZ-2210-V2109:1906808037|1666772973307|-729068160:0] agent is started.
2022-10-31 13:35:04,002 ERROR PerfTestRunnable.java:228 : [138][admin] Error while executing a test: Connection is not completed or cached files digest weren't received until 10 sec
2022-10-31 13:35:04,002 INFO  SingleConsole.java:992 : Sampling is stopped
2022-10-31 13:35:04,004 ERROR TaskUtils.java:95 : Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 0
	at net.grinder.SingleConsole.getPlusResult(SingleConsole.java:934)
	at net.grinder.SingleConsole.unregisterSampling(SingleConsole.java:997)
	at org.ngrinder.perftest.service.PerfTestRunnable.doTerminate(PerfTestRunnable.java:605)
	at org.ngrinder.perftest.service.PerfTestRunnable.doTest(PerfTestRunnable.java:230)
	at org.ngrinder.perftest.service.PerfTestRunnable.doStart(PerfTestRunnable.java:168)
	at org.ngrinder.perftest.service.PerfTestRunnable.startPeriodically(PerfTestRunnable.java:139)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
